spring:
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
        show_sql: true

  datasource:
    url: jdbc:mysql://localhost:3306/popcorn
    username: root
    password: 13241324
    driver-class-name: com.mysql.cj.jdbc.Driver
